ARG BASE_IMAGE=digitalhigh/dreambooth:latest
FROM ${BASE_IMAGE} as cuda-base

WORKDIR /

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV DEBIAN_FRONTEND noninteractive\
    SHELL=/bin/bash

WORKDIR /workspace/

# Create venv
ENV VIRTUAL_ENV=/workspace/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ARG TORCH2

ADD wheels/torch2 /workspace/wheels/

RUN files=$(find /workspace/wheels/ -name "*.whl"); \
    echo "Files " $files; \
    pip install $files;

RUN rm -rf /workspace/wheels/

EXPOSE 22/tcp
EXPOSE 22/udp
EXPOSE 3000/tcp

# Set to have the container update the dreambooth extension on container start.
ENV UPDATE_EXTENSION="false"

# Update the Auto1111 WebUI on container start.
ENV UPDATE_WEBUI="false"

# Set to install torch2. Otherwise, torch 1.1.13 will be used.
ENV TORCH2=$TORCH2

# Set for openSSH access. Runpod automatically sets this if configured in user settings.
ENV PUBLIC_KEY=""

ENV JUPYTER_PASSWORD=""

ENV API_KEY=""

ENV TORCH_REVISION=""

ENV BRANCH="main"

SHELL ["/bin/bash", "--login", "-c"]
